replicaCount: 1

image:
  repository: parkwoodent/sample-microservice
  tag: ${trigger['properties']['TAG']}
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  
ingress:
  hosts:
    - host: dev-sample-microservice.parkwood-digital.com
      paths: ['/']
      
  tls:
  - hosts:
    - dev-sample-microservice.parkwood-digital.com