replicaCount: 1

image:
  repository: parkwoodent/sample-microservice
  tag: ${trigger['tag']}
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  
ingress:
  hosts:
    - host: dev-microservice.parkwood-digital.com
      paths: ['/']